const KEY="fiveStagsFreshBuild";
const $=id=>document.getElementById(id);
const c=$("drumCanvas"),ctx=c.getContext("2d");
const e={draw:$("drawBtn"),reset:$("resetBtn"),remaining:$("remainingCount"),drawn:$("drawnCount"),winnerSmall:$("winnerSmall"),winnerLarge:$("winnerLarge"),history:$("historyList"),sound:$("soundBtn"),settings:$("settingsBtn"),drawer:$("settingsDrawer"),backdrop:$("drawerBackdrop"),closeSettings:$("closeSettingsBtn"),fullscreen:$("fullscreenBtn"),max:$("maxNumber"),apply:$("applyBtn"),setup:$("setupMessage"),countdownToggle:$("countdownToggle"),overlayToggle:$("overlayToggle"),countdown:$("countdownOverlay"),countdownNumber:$("countdownNumber"),overlay:$("winnerOverlay"),closeWinner:$("closeWinnerBtn"),confetti:$("confetti"),confirm:$("confirmDialog"),machine:document.querySelector(".machine")};
let state={maxNumber:200,drawnNumbers:[],currentWinner:null,soundOn:true,countdownOn:true,overlayOn:true};
let balls=[],drawing=false,mix=.28,audio=null;
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Number.isInteger(s.maxNumber)){state={...state,...s};state.drawnNumbers=(s.drawnNumbers||[]).filter(n=>Number.isInteger(n)&&n>=1&&n<=s.maxNumber)}}catch{}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function available(){const u=new Set(state.drawnNumbers),a=[];for(let i=1;i<=state.maxNumber;i++)if(!u.has(i))a.push(i);return a}
function rnd(a,b){return a+Math.random()*(b-a)}
function buildBalls(){const av=available(),vis=av.length<=58?av:[...av].sort(()=>Math.random()-.5).slice(0,58);balls=vis.map(n=>({n,x:rnd(180,780),y:rnd(115,425),vx:rnd(-1.2,1.2),vy:rnd(-1.2,1.2),r:av.length>150?19:22,a:rnd(0,Math.PI*2),spin:rnd(-.04,.04)}))}
function update(){for(const b of balls){const cx=480,cy=280,rx=390-b.r,ry=220-b.r;b.vx+=rnd(-mix,mix);b.vy+=rnd(-mix,mix)+.018;let s=Math.hypot(b.vx,b.vy),m=drawing?7.6:2.6;if(s>m){b.vx=b.vx/s*m;b.vy=b.vy/s*m}b.x+=b.vx;b.y+=b.vy;b.a+=b.spin;const nx=(b.x-cx)/rx,ny=(b.y-cy)/ry;if(nx*nx+ny*ny>1){const nl=Math.sqrt(((b.x-cx)/(rx*rx))**2+((b.y-cy)/(ry*ry))**2)||1,nX=((b.x-cx)/(rx*rx))/nl,nY=((b.y-cy)/(ry*ry))/nl,d=b.vx*nX+b.vy*nY;b.vx=(b.vx-2*d*nX)*.88;b.vy=(b.vy-2*d*nY)*.88;const a=Math.atan2((b.y-cy)/ry,(b.x-cx)/rx);b.x=cx+Math.cos(a)*rx*.985;b.y=cy+Math.sin(a)*ry*.985}}}
function drawBall(b){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.a);const g=ctx.createRadialGradient(-b.r*.35,-b.r*.45,b.r*.1,0,0,b.r);g.addColorStop(0,"#fff8dd");g.addColorStop(.26,"#f1d190");g.addColorStop(1,"#b87723");ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fillStyle=g;ctx.fill();ctx.lineWidth=2;ctx.strokeStyle="rgba(80,45,7,.58)";ctx.stroke();ctx.fillStyle="#172017";ctx.font=`900 ${Math.max(12,b.r*.72)}px Arial`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(b.n,0,1);ctx.restore()}
function loop(){ctx.clearRect(0,0,960,540);update();balls.forEach(drawBall);requestAnimationFrame(loop)}
function render(){const r=state.maxNumber-state.drawnNumbers.length;e.max.value=state.maxNumber;e.remaining.textContent=r;e.drawn.textContent=state.drawnNumbers.length;e.winnerSmall.textContent=state.currentWinner??"—";e.sound.textContent=state.soundOn?"Sound: On":"Sound: Off";e.countdownToggle.checked=state.countdownOn;e.overlayToggle.checked=state.overlayOn;e.draw.disabled=r===0||drawing;e.draw.querySelector("b").textContent=r===0?"ALL TICKETS DRAWN":drawing?"MIXING...":"DRAW A NUMBER";e.setup.textContent=`Tickets 1–${state.maxNumber} loaded. ${r} remaining.`;renderHistory()}
function renderHistory(){e.history.innerHTML="";if(!state.drawnNumbers.length){e.history.innerHTML="<span>No winners yet.</span>";return}[...state.drawnNumbers].reverse().forEach((n,i)=>{const d=document.createElement("div");d.className="history-item";d.innerHTML=`<small>Draw ${state.drawnNumbers.length-i}</small><strong>${n}</strong>`;e.history.appendChild(d)})}
function secureIndex(len){if(crypto?.getRandomValues){const max=0xFFFFFFFF,limit=max-max%len,a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%len}return Math.floor(Math.random()*len)}
function tone(f,d,t="sine",v=.07,delay=0){if(!state.soundOn)return;if(!audio)audio=new(AudioContext||webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime+delay;o.type=t;o.frequency.setValueAtTime(f,now);g.gain.setValueAtTime(v,now);g.gain.exponentialRampToValueAtTime(.001,now+d);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+d)}
async function countdown(){if(!state.countdownOn)return;e.countdown.classList.add("show");for(const n of[3,2,1]){e.countdownNumber.textContent=n;tone(320+n*55,.18,"triangle",.06);await new Promise(r=>setTimeout(r,700))}e.countdown.classList.remove("show")}
async function drawWinner(){if(drawing)return;const av=available();if(!av.length)return;drawing=true;render();if(state.soundOn){if(!audio)audio=new(AudioContext||webkitAudioContext)();if(audio.state==="suspended")await audio.resume()}await countdown();e.machine.classList.add("mixing");mix=1.02;const pulse=setInterval(()=>tone(rnd(105,165),.09,"square",.016),160);await new Promise(r=>setTimeout(r,3300));clearInterval(pulse);const w=av[secureIndex(av.length)];state.currentWinner=w;state.drawnNumbers.push(w);drawing=false;mix=.28;e.machine.classList.remove("mixing");save();buildBalls();render();tone(523,.42,"triangle",.09);tone(659,.42,"triangle",.09,.14);tone(784,.65,"triangle",.1,.28);if(state.overlayOn)setTimeout(()=>showWinner(w),500)}
function showWinner(n){e.winnerLarge.textContent=n;e.overlay.classList.add("show");e.confetti.innerHTML="";for(let i=0;i<95;i++){const p=document.createElement("span");p.className="confetti-piece";p.style.left=`${Math.random()*100}%`;p.style.animationDelay=`${Math.random()*.4}s`;p.style.animationDuration=`${1.7+Math.random()*1.1}s`;p.style.setProperty("--drift",`${-180+Math.random()*360}px`);p.style.background=i%3===0?"#f3d28d":i%3===1?"#a85e43":"#f3ead8";e.confetti.appendChild(p)}}
function closeWinner(){e.overlay.classList.remove("show");e.confetti.innerHTML=""}
function resetNow(){state.drawnNumbers=[];state.currentWinner=null;closeWinner();buildBalls();save();render()}
e.draw.onclick=drawWinner;e.reset.onclick=()=>state.drawnNumbers.length?e.confirm.showModal():resetNow();e.confirm.onclose=()=>{if(e.confirm.returnValue==="confirm")resetNow()};e.settings.onclick=()=>e.drawer.classList.add("open");e.closeSettings.onclick=e.backdrop.onclick=()=>e.drawer.classList.remove("open");e.sound.onclick=()=>{state.soundOn=!state.soundOn;save();render()};e.fullscreen.onclick=async()=>{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()};document.onfullscreenchange=()=>e.fullscreen.textContent=document.fullscreenElement?"Exit full screen":"Full screen";e.apply.onclick=()=>{const n=Number(e.max.value);if(!Number.isInteger(n)||n<1||n>2000){e.setup.textContent="Enter a whole number from 1 to 2,000.";return}if(state.drawnNumbers.length&&!confirm("Changing the range starts a fresh raffle. Continue?"))return;state.maxNumber=n;state.drawnNumbers=[];state.currentWinner=null;buildBalls();save();render();e.drawer.classList.remove("open")};e.countdownToggle.onchange=()=>{state.countdownOn=e.countdownToggle.checked;save()};e.overlayToggle.onchange=()=>{state.overlayOn=e.overlayToggle.checked;save()};e.closeWinner.onclick=closeWinner;e.overlay.onclick=x=>{if(x.target===e.overlay)closeWinner()};load();buildBalls();render();loop();
